// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simple/simple.proto

package simple

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SingleMessage struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsSimple             bool     `protobuf:"varint,2,opt,name=is_simple,json=isSimple,proto3" json:"is_simple,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SampleList           []int32  `protobuf:"varint,4,rep,packed,name=sample_list,json=sampleList,proto3" json:"sample_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleMessage) Reset()         { *m = SingleMessage{} }
func (m *SingleMessage) String() string { return proto.CompactTextString(m) }
func (*SingleMessage) ProtoMessage()    {}
func (*SingleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b3c868e94d57426, []int{0}
}

func (m *SingleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleMessage.Unmarshal(m, b)
}
func (m *SingleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleMessage.Marshal(b, m, deterministic)
}
func (m *SingleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleMessage.Merge(m, src)
}
func (m *SingleMessage) XXX_Size() int {
	return xxx_messageInfo_SingleMessage.Size(m)
}
func (m *SingleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SingleMessage proto.InternalMessageInfo

func (m *SingleMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SingleMessage) GetIsSimple() bool {
	if m != nil {
		return m.IsSimple
	}
	return false
}

func (m *SingleMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SingleMessage) GetSampleList() []int32 {
	if m != nil {
		return m.SampleList
	}
	return nil
}

func init() {
	proto.RegisterType((*SingleMessage)(nil), "SingleMessage")
}

func init() { proto.RegisterFile("simple/simple.proto", fileDescriptor_9b3c868e94d57426) }

var fileDescriptor_9b3c868e94d57426 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xce, 0xcc, 0x2d,
	0xc8, 0x49, 0xd5, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x4a, 0x85, 0x5c, 0xbc, 0xc1,
	0x99, 0x79, 0xe9, 0x39, 0xa9, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x7c, 0x5c, 0x4c,
	0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x4c, 0x99, 0x29, 0x42, 0xd2, 0x5c, 0x9c,
	0x99, 0xc5, 0xf1, 0x10, 0x3d, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x1c, 0x99, 0xc5, 0xc1,
	0x60, 0xbe, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x67,
	0x10, 0x98, 0x2d, 0x24, 0xcf, 0xc5, 0x5d, 0x9c, 0x08, 0x92, 0x8d, 0xcf, 0xc9, 0x2c, 0x2e, 0x91,
	0x60, 0x51, 0x60, 0xd6, 0x60, 0x0d, 0xe2, 0x82, 0x08, 0xf9, 0x64, 0x16, 0x97, 0x24, 0xb1, 0x81,
	0x6d, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x33, 0x56, 0x16, 0x21, 0x90, 0x00, 0x00, 0x00,
}
