// Code generated by protoc-gen-go. DO NOT EDIT.
// source: 9-person-with-package.proto

package person

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// we define the enum with the properties
type Person_EyeColor int32

const (
	Person_UNKNOWN_EYE_COLOR Person_EyeColor = 0
	Person_EYE_GREEN         Person_EyeColor = 1
	Person_EYE_BROWN         Person_EyeColor = 2
	Person_EYE_BLUE          Person_EyeColor = 3
)

var Person_EyeColor_name = map[int32]string{
	0: "UNKNOWN_EYE_COLOR",
	1: "EYE_GREEN",
	2: "EYE_BROWN",
	3: "EYE_BLUE",
}

var Person_EyeColor_value = map[string]int32{
	"UNKNOWN_EYE_COLOR": 0,
	"EYE_GREEN":         1,
	"EYE_BROWN":         2,
	"EYE_BLUE":          3,
}

func (x Person_EyeColor) String() string {
	return proto.EnumName(Person_EyeColor_name, int32(x))
}

func (Person_EyeColor) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_769c4d55c11a0cb1, []int{0, 0}
}

type Person struct {
	Age               int32   `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	FirstName         string  `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName          string  `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	SmallPicture      []byte  `protobuf:"bytes,4,opt,name=small_picture,json=smallPicture,proto3" json:"small_picture,omitempty"`
	IsProfileVerified bool    `protobuf:"varint,5,opt,name=is_profile_verified,json=isProfileVerified,proto3" json:"is_profile_verified,omitempty"`
	Height            float32 `protobuf:"fixed32,6,opt,name=height,proto3" json:"height,omitempty"`
	// a list of phone numbers, optional
	PhoneNumber []string `protobuf:"bytes,7,rep,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// we use the enum. The tag should
	// continue from the last message field
	EyeColor Person_EyeColor `protobuf:"varint,8,opt,name=eye_color,json=eyeColor,proto3,enum=person.Person_EyeColor" json:"eye_color,omitempty"`
	// persons' birthdate
	Birthdate *Date `protobuf:"bytes,9,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	// multiple addresses
	Addresses            []*Person_Address `protobuf:"bytes,10,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_769c4d55c11a0cb1, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Person) GetSmallPicture() []byte {
	if m != nil {
		return m.SmallPicture
	}
	return nil
}

func (m *Person) GetIsProfileVerified() bool {
	if m != nil {
		return m.IsProfileVerified
	}
	return false
}

func (m *Person) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Person) GetPhoneNumber() []string {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

func (m *Person) GetEyeColor() Person_EyeColor {
	if m != nil {
		return m.EyeColor
	}
	return Person_UNKNOWN_EYE_COLOR
}

func (m *Person) GetBirthdate() *Date {
	if m != nil {
		return m.Birthdate
	}
	return nil
}

func (m *Person) GetAddresses() []*Person_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

// define the type Address within Person
type Person_Address struct {
	AddressLine_1        string   `protobuf:"bytes,1,opt,name=address_line_1,json=addressLine1,proto3" json:"address_line_1,omitempty"`
	AddressLine_2        string   `protobuf:"bytes,2,opt,name=address_line_2,json=addressLine2,proto3" json:"address_line_2,omitempty"`
	ZipCode              string   `protobuf:"bytes,3,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person_Address) Reset()         { *m = Person_Address{} }
func (m *Person_Address) String() string { return proto.CompactTextString(m) }
func (*Person_Address) ProtoMessage()    {}
func (*Person_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_769c4d55c11a0cb1, []int{0, 0}
}

func (m *Person_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_Address.Unmarshal(m, b)
}
func (m *Person_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_Address.Marshal(b, m, deterministic)
}
func (m *Person_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_Address.Merge(m, src)
}
func (m *Person_Address) XXX_Size() int {
	return xxx_messageInfo_Person_Address.Size(m)
}
func (m *Person_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Person_Address proto.InternalMessageInfo

func (m *Person_Address) GetAddressLine_1() string {
	if m != nil {
		return m.AddressLine_1
	}
	return ""
}

func (m *Person_Address) GetAddressLine_2() string {
	if m != nil {
		return m.AddressLine_2
	}
	return ""
}

func (m *Person_Address) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

func (m *Person_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Person_Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func init() {
	proto.RegisterEnum("person.Person_EyeColor", Person_EyeColor_name, Person_EyeColor_value)
	proto.RegisterType((*Person)(nil), "person.Person")
	proto.RegisterType((*Person_Address)(nil), "person.Person.Address")
}

func init() { proto.RegisterFile("9-person-with-package.proto", fileDescriptor_769c4d55c11a0cb1) }

var fileDescriptor_769c4d55c11a0cb1 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xd1, 0x6e, 0xd3, 0x30,
	0x18, 0x85, 0xc9, 0xda, 0xb5, 0xf1, 0xdf, 0x76, 0xea, 0x8c, 0x18, 0xd9, 0x26, 0xa4, 0x30, 0xb8,
	0x88, 0x84, 0x1a, 0x69, 0x85, 0x0b, 0xb8, 0x84, 0x12, 0x71, 0x41, 0x49, 0x2b, 0x4b, 0x63, 0xe2,
	0xca, 0x72, 0x93, 0xbf, 0xad, 0xb5, 0x34, 0x8e, 0x1c, 0x17, 0xd4, 0x3d, 0x0c, 0xaf, 0xc8, 0x2b,
	0xa0, 0x38, 0x89, 0x86, 0x80, 0xbb, 0xff, 0x9c, 0xef, 0x48, 0x96, 0xce, 0x31, 0x5c, 0xbe, 0x9b,
	0x14, 0xa8, 0x4b, 0x95, 0x4f, 0x7e, 0x48, 0xb3, 0x9d, 0x14, 0x22, 0xb9, 0x13, 0x1b, 0x0c, 0x0b,
	0xad, 0x8c, 0xa2, 0xbd, 0x1a, 0x5d, 0x9c, 0xbf, 0x9d, 0xa4, 0xc2, 0xe0, 0x7f, 0x22, 0x57, 0xbf,
	0xba, 0xd0, 0x5b, 0xda, 0x14, 0x1d, 0x43, 0x47, 0x6c, 0xd0, 0x73, 0x7c, 0x27, 0x38, 0x66, 0xd5,
	0x49, 0x9f, 0x01, 0xac, 0xa5, 0x2e, 0x0d, 0xcf, 0xc5, 0x0e, 0xbd, 0x23, 0xdf, 0x09, 0x08, 0x23,
	0xd6, 0x89, 0xc5, 0x0e, 0xe9, 0x25, 0x90, 0x4c, 0xb4, 0xb4, 0x63, 0xa9, 0x5b, 0x19, 0x16, 0xbe,
	0x80, 0x51, 0xb9, 0x13, 0x59, 0xc6, 0x0b, 0x99, 0x98, 0xbd, 0x46, 0xaf, 0xeb, 0x3b, 0xc1, 0x90,
	0x0d, 0xad, 0xb9, 0xac, 0x3d, 0x1a, 0xc2, 0x63, 0x59, 0xf2, 0x42, 0xab, 0xb5, 0xcc, 0x90, 0x7f,
	0x47, 0x2d, 0xd7, 0x12, 0x53, 0xef, 0xd8, 0x77, 0x02, 0x97, 0x9d, 0xca, 0x72, 0x59, 0x93, 0xaf,
	0x0d, 0xa0, 0x67, 0xd0, 0xdb, 0xa2, 0xdc, 0x6c, 0x8d, 0xd7, 0xf3, 0x9d, 0xe0, 0x88, 0x35, 0x8a,
	0x3e, 0x87, 0x61, 0xb1, 0x55, 0x39, 0xf2, 0x7c, 0xbf, 0x5b, 0xa1, 0xf6, 0xfa, 0x7e, 0x27, 0x20,
	0x6c, 0x60, 0xbd, 0xd8, 0x5a, 0xf4, 0x0d, 0x10, 0x3c, 0x20, 0x4f, 0x54, 0xa6, 0xb4, 0xe7, 0xfa,
	0x4e, 0x70, 0x32, 0x7d, 0x1a, 0xd6, 0xfd, 0x84, 0x75, 0x01, 0x61, 0x74, 0xc0, 0x59, 0x85, 0x99,
	0x8b, 0xcd, 0x45, 0x5f, 0x01, 0x59, 0x49, 0x6d, 0xb6, 0x55, 0x7d, 0x1e, 0xf1, 0x9d, 0x60, 0x30,
	0x1d, 0x85, 0x95, 0x58, 0xde, 0x6d, 0xc2, 0x8f, 0xc2, 0x20, 0x7b, 0xe0, 0xd5, 0x13, 0x22, 0x4d,
	0x35, 0x96, 0x25, 0x96, 0x1e, 0xf8, 0x9d, 0x60, 0x30, 0x3d, 0xfb, 0xeb, 0x89, 0xf7, 0x35, 0x67,
	0x0f, 0xc1, 0x8b, 0x9f, 0x0e, 0xf4, 0x1b, 0x9b, 0xbe, 0x84, 0x93, 0x06, 0xf0, 0x4c, 0xe6, 0xc8,
	0xaf, 0xed, 0x1a, 0x84, 0x0d, 0x1b, 0x77, 0x2e, 0x73, 0xbc, 0xfe, 0x27, 0x35, 0x6d, 0xa6, 0xf9,
	0x33, 0x35, 0xa5, 0xe7, 0xe0, 0xde, 0xcb, 0x82, 0x27, 0x2a, 0x6d, 0xc7, 0xe9, 0xdf, 0xcb, 0x62,
	0xa6, 0x52, 0xa4, 0x14, 0xba, 0x89, 0x34, 0x07, 0x3b, 0x09, 0x61, 0xf6, 0xa6, 0x1e, 0xf4, 0x13,
	0xb5, 0xcf, 0x8d, 0x3e, 0xd8, 0xfa, 0x09, 0x6b, 0xe5, 0xd5, 0x17, 0x70, 0xdb, 0x66, 0xe8, 0x13,
	0x38, 0xbd, 0x89, 0x3f, 0xc7, 0x8b, 0xdb, 0x98, 0x47, 0xdf, 0x22, 0x3e, 0x5b, 0xcc, 0x17, 0x6c,
	0xfc, 0x88, 0x8e, 0x80, 0x54, 0xf2, 0x13, 0x8b, 0xa2, 0x78, 0xec, 0xb4, 0xf2, 0x03, 0x5b, 0xdc,
	0xc6, 0xe3, 0x23, 0x3a, 0x04, 0xd7, 0xca, 0xf9, 0x4d, 0x34, 0xee, 0xac, 0x7a, 0xf6, 0xe3, 0xbd,
	0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x79, 0x2b, 0x06, 0xba, 0xba, 0x02, 0x00, 0x00,
}
